apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: canarypilot-backend-stable-hpa
  namespace: canarypilot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canarypilot-backend-stable
  minReplicas: 1
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: canarypilot-backend-canary-hpa
  namespace: canarypilot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canarypilot-backend-canary
  minReplicas: 0
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
